COMPILER= iverilog

all: $(wildcard *.v)
	$(COMPILER) -o ALUand_tb ALUand_tb.v 
	$(COMPILER) -o ALUarithmeticShiftLeft_tb ALUarithmeticShiftLeft_tb.v 
	$(COMPILER) -o ALUcompA2_tb ALUcompA2_tb.v 
	$(COMPILER) -o ALUdecoder_tb ALUdecoder_tb.v 
	$(COMPILER) -o ALUnot_tb ALUnot_tb.v 
	$(COMPILER) -o ALUor_tb ALUor_tb.v 
	$(COMPILER) -o ALUoutputSelector_tb ALUoutputSelector_tb.v
	$(COMPILER) -o ALUresta_tb ALUresta_tb.v 
	$(COMPILER) -o ALUsuma_tb ALUsuma_tb.v 
	$(COMPILER) -o ALUxor_tb ALUxor_tb.v 
	$(COMPILER) -o fulladder_tb fulladder_tb.v
	$(COMPILER) -o inputBitSet_tb inputBitSet_tb.v
	$(COMPILER) -o inputWordSet_tb inputWordSet_tb.v

ALUarithmeticShiftLeft_tb: ALUarithmeticShiftLeft_tb.v
	$(COMPILER) -o ALUarithmeticShiftLeft_tb ALUarithmeticShiftLeft_tb.v 

ALUcompA2_tb: ALUcompA2_tb.v
	$(COMPILER) -o ALUcompA2_tb ALUcompA2_tb.v 

ALUdecoder_tb:
	$(COMPILER) -o ALUdecoder_tb ALUdecoder_tb.v 

ALUnot_tb: ALUnot_tb.v 
	$(COMPILER) -o ALUnot_tb ALUnot_tb.v 

ALUor_tb: ALUor_tb.v 
	$(COMPILER) -o ALUor_tb ALUor_tb.v 

ALUoutputSelector_tb: ALUoutputSelector_tb.v
	$(COMPILER) -o ALUoutputSelector_tb ALUoutputSelector_tb.v

ALUresta_tb: ALUresta_tb.v
	$(COMPILER) -o ALUresta_tb ALUresta_tb.v 

ALUsuma_tb: ALUsuma_tb.v 
	$(COMPILER) -o ALUsuma_tb ALUsuma_tb.v 

ALUxor_tb: ALUxor_tb.v
	$(COMPILER) -o ALUxor_tb ALUxor_tb.v 

fulladder_tb: fulladder_tb.v
	$(COMPILER) -o fulladder_tb fulladder_tb.v

inputBitSet_tb: inputBitSet_tb.v
	$(COMPILER) -o inputBitSet_tb inputBitSet_tb.v

inputWordSet_tb: inputWordSet_tb.v
	$(COMPILER) -o inputWordSet_tb inputWordSet_tb.v

ALUand_tb: ALUand_tb.v
	$(COMPILER) -o ALUand_tb ALUand_tb.v 

	
